# Generated by Django 6.0.3 on 2026-06-04 02:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APKVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(help_text='Ex: 1.0.0', max_length=20, unique=True)),
                ('apk_file', models.FileField(upload_to='apk_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['apk'])])),
                ('release_notes', models.TextField(blank=True, help_text='Notes de version (changements, améliorations)')),
                ('is_active', models.BooleanField(default=True, help_text='Version disponible au téléchargement')),
                ('min_android_version', models.CharField(default='5.0', help_text="Version minimale d'Android requise", max_length=10)),
                ('file_size', models.BigIntegerField(default=0, help_text='Taille du fichier en bytes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('download_count', models.IntegerField(default=0, help_text='Nombre de téléchargements')),
            ],
            options={
                'verbose_name': 'Version APK',
                'verbose_name_plural': 'Versions APK',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PWAConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(default='SDI Marché', max_length=100)),
                ('short_name', models.CharField(default='SDI Market', max_length=12)),
                ('description', models.TextField(default='Plateforme e-commerce mondiale')),
                ('icon_192', models.ImageField(help_text='Icône PWA 192x192px', upload_to='pwa_assets/')),
                ('icon_512', models.ImageField(help_text='Icône PWA 512x512px', upload_to='pwa_assets/')),
                ('splash_screen', models.ImageField(blank=True, help_text='Écran de démarrage (1920x1080px recommandé)', null=True, upload_to='pwa_assets/')),
                ('theme_color', models.CharField(default='#0066FF', help_text='Couleur principale (format #RRGGBB)', max_length=7)),
                ('background_color', models.CharField(default='#FFFFFF', help_text='Couleur de fond (format #RRGGBB)', max_length=7)),
                ('is_enabled', models.BooleanField(default=True)),
                ('start_url', models.CharField(default='/', max_length=200)),
                ('scope', models.CharField(default='/', max_length=200)),
                ('orientation', models.CharField(choices=[('portrait', 'Portrait'), ('landscape', 'Landscape'), ('any', 'Any')], default='portrait', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration PWA',
                'verbose_name_plural': 'Configuration PWA',
            },
        ),
        migrations.CreateModel(
            name='InstallationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_type', models.CharField(choices=[('apk', 'APK'), ('pwa', 'PWA')], max_length=10)),
                ('user_agent', models.TextField(blank=True)),
                ('device_type', models.CharField(choices=[('mobile', 'Mobile'), ('tablet', 'Tablet'), ('desktop', 'Desktop')], default='mobile', max_length=20)),
                ('os_type', models.CharField(blank=True, help_text='iOS, Android, Windows, macOS, Linux, etc.', max_length=50)),
                ('browser', models.CharField(blank=True, help_text='Chrome, Safari, Firefox, etc.', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('apk_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installations', to='app_installer.apkversion')),
            ],
            options={
                'verbose_name': 'Installation Log',
                'verbose_name_plural': 'Installation Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='app_install_timesta_d46a3c_idx'), models.Index(fields=['installation_type'], name='app_install_install_a2eef5_idx')],
            },
        ),
    ]
