# Generated by Django 6.0.3 on 2026-04-06 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_rename_total_wallet_balance_remove_transaction_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAddTransaction',
            fields=[
            ],
            options={
                'verbose_name': 'Versement admin',
                'verbose_name_plural': 'Versements admin',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('marketplace.transaction',),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('awaiting_delivery', 'Awaiting Delivery'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
    ]
