# Generated by Django 6.0.3 on 2026-04-06 21:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_order_delivery_confirmed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_confirmed_at',
        ),
        migrations.AddField(
            model_name='order',
            name='date_achat',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='order',
            name='date_reception_confirmee',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
