# Generated by Django 6.0.3 on 2026-04-07 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_remove_order_delivery_confirmed_at_order_date_achat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_role_management', models.BooleanField(default=False, verbose_name='Activer la gestion des rôles et permissions')),
                ('enable_financial_audit', models.BooleanField(default=False, verbose_name='Activer la traçabilité financière')),
                ('enable_alerts', models.BooleanField(default=False, verbose_name="Activer le système d'alertes intelligentes")),
                ('enable_rollback', models.BooleanField(default=False, verbose_name='Activer le système de rollback')),
                ('enable_dispute_management', models.BooleanField(default=False, verbose_name='Activer la gestion des litiges')),
            ],
            options={
                'verbose_name': 'Paramètre système',
                'verbose_name_plural': 'Paramètres système',
            },
        ),
    ]
