# Generated by Django 6.0.3 on 2026-04-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin_secondary', 'Admin secondaire'), ('support_employee', 'Soutien / employé'), ('buyer_seller', 'Acheteur / Vendeur'), ('delivery_employee', 'Employé livraison'), ('agent', 'Agent')], default='buyer_seller', max_length=20),
        ),
    ]
