# Generated by Django 6.0.3 on 2026-04-07 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_category_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Image du produit', upload_to='products/%Y/%m/')),
                ('is_primary', models.BooleanField(default=False, help_text='Image affichée par défaut')),
                ('alt_text', models.CharField(blank=True, help_text="Description pour l'accessibilité", max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='marketplace.product')),
            ],
            options={
                'verbose_name': 'Image du produit',
                'verbose_name_plural': 'Images du produit',
                'ordering': ['sort_order', 'uploaded_at'],
            },
        ),
    ]
