# Generated by Django 6.0.3 on 2026-04-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0017_exchangerate_user_can_request_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='custom_image',
            field=models.ImageField(blank=True, help_text='Image personnalisée uploadée', null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(blank=True, help_text='Image générée automatiquement', null=True),
        ),
    ]
