# Generated by Django 6.0.3 on 2026-04-09 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0019_chat_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessageRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_receipts', to='marketplace.chatmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_message_reads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lecture de message',
                'verbose_name_plural': 'Lectures de messages',
                'unique_together': {('message', 'user')},
            },
        ),
    ]
