# Generated by Django 6.0.3 on 2026-04-10 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0023_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hauteur',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Hauteur en cm', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='largeur',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Largeur en cm', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='longueur',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Longueur en cm', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='poids',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Poids en kg', max_digits=10, null=True),
        ),
    ]
