# Generated by Django 6.0.3 on 2026-04-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0024_product_hauteur_product_largeur_product_longueur_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminaddtransaction',
            options={'ordering': ['-created_at'], 'verbose_name': "Ajout d'argent", 'verbose_name_plural': "Ajouts d'argent"},
        ),
        migrations.AddField(
            model_name='deliveryassignment',
            name='driver_address_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryassignment',
            name='driver_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='deliveryassignment',
            name='driver_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='buyer_address_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='buyer_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='buyer_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
