# Generated by Django 6.0.3 on 2026-04-23 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0025_alter_adminaddtransaction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude de la boutique', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude de la boutique', max_digits=9, null=True),
        ),
    ]
