# Generated by Django 6.0.3 on 2026-04-26 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0028_order_distance_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='commission_balance_htg',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Comptes Livreur Multi-Devises - HTG', max_digits=15),
        ),
        migrations.AddField(
            model_name='wallet',
            name='commission_balance_peso',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Comptes Livreur Multi-Devises - PESO', max_digits=15),
        ),
        migrations.AddField(
            model_name='wallet',
            name='commission_balance_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Comptes Livreur Multi-Devises - USD', max_digits=15),
        ),
    ]
