# Generated by Django 6.0.3 on 2026-04-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0029_add_commission_balances'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_code',
            field=models.CharField(blank=True, help_text='Code OTP temporaire (6 chiffres)', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_expires_at',
            field=models.DateTimeField(blank=True, help_text='Expiration du code OTP', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='security_pin',
            field=models.CharField(blank=True, help_text='Code PIN utilisateur (8 chiffres)', max_length=8, null=True),
        ),
    ]
