# Generated by Django 6.0.3 on 2026-04-27 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0030_add_security_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='last_assigned_delivery_employee_index',
            field=models.PositiveIntegerField(default=0, help_text='Index du dernier livreur assigné (round-robin)'),
        ),
    ]
