# Generated by Django 6.0.3 on 2026-04-27 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0031_systemsettings_last_assigned_delivery_employee_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordManagementPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view_passwords', models.BooleanField(default=False, verbose_name='Peut voir les mots de passe')),
                ('can_change_passwords', models.BooleanField(default=False, verbose_name='Peut modifier les mots de passe')),
                ('can_manage_other_admins', models.BooleanField(default=False, verbose_name='Peut gérer les autres admins')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='password_management_permissions', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permission de Gestion des Mots de Passe',
                'verbose_name_plural': 'Permissions de Gestion des Mots de Passe',
                'unique_together': {('admin',)},
            },
        ),
    ]
