# Generated by Django 6.0.3 on 2026-04-28 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0032_passwordmanagementpermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersistentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_sound_at', models.DateTimeField(blank=True, null=True)),
                ('sound_interval_minutes', models.PositiveIntegerField(default=1)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persistent_notifications', to=settings.AUTH_USER_MODEL)),
                ('related_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketplace.deliveryassignment')),
            ],
            options={
                'verbose_name': 'Notification persistante',
                'verbose_name_plural': 'Notifications persistantes',
                'ordering': ['-created_at'],
            },
        ),
    ]
