# Generated by Django 6.0.3 on 2026-05-01 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0035_add_eur_wallet_balances'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerate',
            name='eur_to_htg',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='eur_to_peso',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='eur_to_usd',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='order',
            name='admin_notification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='admin_notified',
            field=models.BooleanField(default=False, help_text="L'admin a été notifié de la livraison"),
        ),
        migrations.AddField(
            model_name='order',
            name='driver_confirmed_at',
            field=models.DateTimeField(blank=True, help_text='Moment où le livreur a confirmé', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='driver_confirmed_delivery',
            field=models.BooleanField(default=False, help_text='Le livreur a confirmé la livraison'),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_currency',
            field=models.CharField(choices=[('USD', 'USD'), ('HTG', 'HTG'), ('DOP', 'DOP'), ('EUR', 'EUR')], default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(default='HTG', max_length=10),
        ),
        migrations.AlterField(
            model_name='deliveryassignment',
            name='driver_confirmed_delivery',
            field=models.BooleanField(default=False, help_text='Le livreur a confirmé la livraison'),
        ),
        migrations.AlterField(
            model_name='order',
            name='buyer_confirmed_at',
            field=models.DateTimeField(blank=True, help_text="Moment où l'acheteur a confirmé", null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='buyer_confirmed_delivery',
            field=models.BooleanField(default=False, help_text="L'acheteur a confirmé la réception"),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, help_text='Montant total en USD (devise interne)', max_digits=15),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price_ht',
            field=models.DecimalField(decimal_places=2, help_text='Prix en USD (devise interne)', max_digits=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_ht',
            field=models.DecimalField(decimal_places=2, help_text='Prix en USD (devise interne)', max_digits=15),
        ),
    ]
