# Generated by Django 6.0.3 on 2026-05-02 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0038_order_payment_methods'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='failed_withdrawal_attempts',
            field=models.IntegerField(default=0, help_text='Tentatives de retrait échouées'),
        ),
        migrations.AddField(
            model_name='user',
            name='withdrawal_blocked_until',
            field=models.DateTimeField(blank=True, help_text="Bloqué jusqu'à cette date", null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('htg_wallet', 'HTG - Portefeuille / MonCash / NatCash'), ('htg_moncash', 'HTG - MonCash'), ('htg_natcash', 'HTG - NatCash'), ('htg_cod', 'HTG - Cash à la livraison'), ('htg_transfer', 'HTG - Virement local HTG'), ('dop_tpag', 'DOP - tPago'), ('dop_local_transfer', 'DOP - Virement local DOP'), ('eur_card', 'EUR - Carte Visa/Mastercard'), ('eur_paypal', 'EUR - PayPal'), ('int_card', 'International - Carte Visa/Mastercard'), ('int_paypal', 'International - PayPal')], default='htg_wallet', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_code',
            field=models.CharField(blank=True, help_text='Code OTP hashé temporaire', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='security_pin',
            field=models.CharField(blank=True, help_text='Code PIN hashé utilisateur', max_length=128, null=True),
        ),
    ]
