# Generated by Django 6.0.3 on 2026-05-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0039_user_failed_withdrawal_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_code',
            field=models.CharField(blank=True, help_text='Code de compte unique', max_length=20),
        ),
    ]
