# Generated by Django 6.0.3 on 2026-05-05 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0040_user_account_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='microsdicash_account_name',
            field=models.CharField(default='MicroSDICash', max_length=255, verbose_name='Nom du compte MicroSDICash'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='microsdicash_account_number',
            field=models.CharField(default='44481629', max_length=50, verbose_name='Numéro du compte MicroSDICash'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='microsdicash_account_phone',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Téléphone du compte MicroSDICash'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='microsdicash_payment_instructions',
            field=models.TextField(blank=True, default='Rechargez votre compte via l’administration SDI Marché Mondial ou via un agent local.', verbose_name='Instructions de paiement MicroSDICash'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('htg_wallet', 'HTG - MicroSDICash / MonCash / NatCash'), ('htg_moncash', 'HTG - MonCash'), ('htg_natcash', 'HTG - NatCash'), ('htg_cod', 'HTG - Cash à la livraison'), ('htg_transfer', 'HTG - Virement local HTG'), ('dop_tpag', 'DOP - tPago'), ('dop_local_transfer', 'DOP - Virement local DOP'), ('eur_card', 'EUR - Carte Visa/Mastercard'), ('eur_paypal', 'EUR - PayPal'), ('int_card', 'International - Carte Visa/Mastercard'), ('int_paypal', 'International - PayPal')], default='htg_wallet', max_length=50),
        ),
    ]
