# Generated by Django 6.0.3 on 2026-05-05 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0042_profile_receipt_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='microsdicash_payment_instructions',
            field=models.TextField(blank=True, default='Rechargez votre compte via l’administration SDI Marché Mondial ou via un agent local. Vous pouvez aussi envoyer l’argent sur MonCash et télécharger le reçu ici.', verbose_name='Instructions de paiement MicroSDICash'),
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_image', models.ImageField(upload_to='receipts/', verbose_name='Image du reçu')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'En attente de vérification'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='Notes administrateur')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processed_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['super_admin', 'admin_secondary']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_receipts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reçu MonCash',
                'verbose_name_plural': 'Reçus MonCash',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
