# Generated by Django 6.0.3 on 2026-05-05 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0043_alter_systemsettings_microsdicash_payment_instructions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='withdrawal_pin',
            field=models.CharField(blank=True, help_text='Code PIN visible pour retrait', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='withdrawal_code',
            field=models.CharField(blank=True, help_text='Code final visible pour retrait', max_length=4, null=True),
        ),
    ]
# Generated by Django 6.0.3 on 2026-05-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0043_alter_systemsettings_microsdicash_payment_instructions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='withdrawal_pin',
            field=models.CharField(blank=True, help_text='Code PIN visible pour retrait', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='withdrawal_code',
            field=models.CharField(blank=True, help_text='Code final visible pour retrait', max_length=4, null=True),
        ),
    ]
