# Generated by Django 6.0.3 on 2026-05-06 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0045_merge_migrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_original',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix original saisi par le vendeur dans la devise choisie', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price_original_currency',
            field=models.CharField(blank=True, choices=[('USD', 'USD ($)'), ('HTG', 'Gourdes (HTG)'), ('DOP', 'Peso Dominicain (DOP)'), ('EUR', 'Euro (€)')], default='USD', help_text='Devise du prix saisi par le vendeur', max_length=3, null=True),
        ),
    ]
