# Generated by Django 6.0.3 on 2026-05-07 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0046_product_price_original_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('brute_force', 'Brute force'), ('injection', 'Injection SQL / XSS'), ('suspicious_access', 'Accès suspect'), ('malware', 'Malware / fichier malveillant'), ('other', 'Autre')], default='other', max_length=50)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Alerte'), ('critical', 'Critique')], default='warning', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('source_ip', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Incident de cybersécurité',
                'verbose_name_plural': 'Incidents de cybersécurité',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='emergency_lockdown',
            field=models.BooleanField(default=False, verbose_name="Mode verrouillage d'urgence"),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='enable_cybersecurity',
            field=models.BooleanField(default=False, verbose_name='Activer la surveillance cybersécurité'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
