# Generated by Django 6.0.3 on 2026-05-08 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0048_add_security_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminWithdrawalPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_confirm_withdrawals', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Permission de Confirmation de Retrait',
                'verbose_name_plural': 'Permissions de Confirmation de Retrait',
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(max_length=10)),
                ('account_type', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'En attente de confirmation'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='pending', max_length=20)),
                ('amount_debited', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('receipt_generated', models.BooleanField(default=False)),
                ('receipt_sent_to_email', models.BooleanField(default=False)),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='withdrawal_receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Demande de Retrait',
                'verbose_name_plural': 'Demandes de Retrait',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='securityevent',
            name='marketplace_se_created_at_idx',
        ),
        migrations.RemoveIndex(
            model_name='securityevent',
            name='marketplace_se_source_ip_created_at_idx',
        ),
        migrations.RemoveIndex(
            model_name='securityevent',
            name='marketplace_se_event_type_created_at_idx',
        ),
        migrations.AlterField(
            model_name='ipblocklist',
            name='blocked_until',
            field=models.DateTimeField(blank=True, help_text="Date d'expiration du blocage (None = permanent)", null=True),
        ),
        migrations.AlterField(
            model_name='ipblocklist',
            name='reason',
            field=models.CharField(blank=True, help_text='Raison du blocage', max_length=255),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='method',
            field=models.CharField(blank=True, help_text='GET, POST, PUT, DELETE, etc.', max_length=10),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='path',
            field=models.CharField(blank=True, help_text='URL accédée', max_length=255),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='response_time_ms',
            field=models.IntegerField(blank=True, help_text='Temps réponse en ms', null=True),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='status_code',
            field=models.IntegerField(blank=True, help_text='Code HTTP réponse', null=True),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['-created_at'], name='marketplace_created_79f464_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['source_ip', '-created_at'], name='marketplace_source__80bde4_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['event_type', '-created_at'], name='marketplace_event_t_3b3c2c_idx'),
        ),
        migrations.AddField(
            model_name='adminwithdrawalpermission',
            name='admin',
            field=models.OneToOneField(limit_choices_to={'role': 'admin_secondary'}, on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_permission', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminwithdrawalpermission',
            name='granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_withdrawal_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_withdrawals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
