# Generated by Django 6.0.3 on 2026-05-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0049_adminwithdrawalpermission_withdrawalrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='identity_document',
            field=models.ImageField(blank=True, null=True, upload_to='identity_documents/', verbose_name="Carte d'identité / Carte SDI"),
        ),
    ]
