# Generated by Django 6.0.3 on 2026-05-09 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0050_profile_identity_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='global_withdrawal_access_granted',
            field=models.BooleanField(default=False, help_text='Accès aux retraits globaux pour les admins secondaires'),
        ),
    ]
