# Generated by Django 6.0.3 on 2026-05-11 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0051_profile_global_withdrawal_access_granted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipblocklist',
            options={},
        ),
        migrations.RemoveField(
            model_name='ipblocklist',
            name='blocked_until',
        ),
        migrations.RemoveField(
            model_name='ipblocklist',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ipblocklist',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='ipblocklist',
            name='is_active',
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_type', models.CharField(choices=[('main', 'Logo Principal'), ('favicon', 'Favicon'), ('footer', 'Logo Footer')], max_length=50, unique=True, verbose_name='Type de configuration')),
                ('image', models.ImageField(upload_to='site_config/%Y/%m/', verbose_name='Image/Logo')),
                ('alt_text', models.CharField(blank=True, help_text="Texte alternatif pour l'image", max_length=255)),
                ('width', models.IntegerField(blank=True, default=200, help_text='Largeur en pixels')),
                ('height', models.IntegerField(blank=True, default=60, help_text='Hauteur en pixels')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_updates', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Configuration du site',
                'verbose_name_plural': 'Configurations du site',
                'ordering': ['config_type'],
            },
        ),
    ]
