# Generated by Django 6.0.3 on 2026-05-11 04:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0052_alter_ipblocklist_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipblocklist',
            options={'ordering': ['ip_address'], 'verbose_name': 'IP bloquée', 'verbose_name_plural': 'IPs bloquées'},
        ),
        migrations.CreateModel(
            name='SiteConfigurationPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_edit_logos', models.BooleanField(default=False, verbose_name='Autorisé à modifier les logos')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'octroi")),
                ('granted_by', models.ForeignKey(blank=True, help_text='Admin principal qui a accordé cette permission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_logo_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Permission accordée par')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logo_permission', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur autorisé')),
            ],
            options={
                'verbose_name': 'Permission de modification des logos',
                'verbose_name_plural': 'Permissions de modification des logos',
            },
        ),
    ]
