# Generated by Django 6.0.3 on 2026-05-12 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0053_alter_ipblocklist_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='site_theme_3d',
            field=models.BooleanField(default=False, verbose_name='Activer thème 3D Arctic Cyber'),
        ),
    ]
