# Generated by Django 6.0.3 on 2026-05-13 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0054_theme_3d_permission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='site_theme_3d',
        ),
        migrations.AddField(
            model_name='profile',
            name='theme_name',
            field=models.CharField(choices=[('arctic-neon-glass', 'Arctic Neon Glass UI'), ('cyber-ice-fintech', 'Cyber Ice Fintech'), ('white-blue-cyber', 'White & Blue Cyber Glassmorphism'), ('quantum-fintech', 'Quantum Fintech Dashboard'), ('neon-flow-banking', 'Neon Flow Banking UI'), ('custom', 'Custom Theme')], default='arctic-neon-glass', help_text='Selected UI theme', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='theme_settings',
            field=models.JSONField(blank=True, default=dict, help_text='Custom theme color settings'),
        ),
    ]
