# Generated by Django 6.0.3 on 2026-05-14 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0055_remove_systemsettings_site_theme_3d_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIThreatAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threat_score', models.FloatField(default=0.0, help_text='Score de menace IA (0-100)')),
                ('threat_level', models.CharField(choices=[('safe', 'Sûr'), ('low', 'Faible'), ('medium', 'Moyen'), ('high', 'Élevé'), ('critical', 'Critique')], default='safe', max_length=20)),
                ('detected_anomalies', models.JSONField(blank=True, default=dict)),
                ('bot_detections', models.IntegerField(default=0)),
                ('brute_force_attempts', models.IntegerField(default=0)),
                ('sql_injection_attempts', models.IntegerField(default=0)),
                ('xss_attempts', models.IntegerField(default=0)),
                ('suspicious_patterns', models.JSONField(blank=True, default=dict)),
                ('ai_confidence', models.FloatField(default=0.0, help_text="Confiance de l'analyse IA (0-1)")),
                ('last_analysis', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Analyse IA Menaces',
                'verbose_name_plural': 'Analyses IA Menaces',
            },
        ),
        migrations.CreateModel(
            name='HoneypotEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('admin_access', 'Accès faux admin'), ('login_attempt', 'Tentative connexion'), ('file_upload', 'Upload fichier'), ('sql_injection', 'Injection SQL'), ('xss_attempt', 'Tentative XSS'), ('brute_force', 'Brute force'), ('other', 'Autre')], default='other', max_length=50)),
                ('source_ip', models.CharField(max_length=50)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('attempted_username', models.CharField(blank=True, max_length=100)),
                ('attempted_password', models.CharField(blank=True, max_length=100)),
                ('payload', models.TextField(blank=True)),
                ('device_info', models.JSONField(blank=True, default=dict)),
                ('geolocation', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alerted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Événement Honeypot',
                'verbose_name_plural': 'Événements Honeypot',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField(choices=[(80, 'HTTP (80)'), (443, 'HTTPS (443)'), (22, 'SSH (22)'), (3306, 'MySQL (3306)'), (8080, 'HTTP Alt (8080)'), (8443, 'HTTPS Alt (8443)'), (21, 'FTP (21)'), (25, 'SMTP (25)'), (53, 'DNS (53)'), (110, 'POP3 (110)'), (143, 'IMAP (143)'), (993, 'IMAPS (993)'), (995, 'POP3S (995)')], unique=True)),
                ('is_open', models.BooleanField(default=False)),
                ('traffic_count', models.IntegerField(default=0)),
                ('suspicious_activity', models.BooleanField(default=False)),
                ('risk_level', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyen'), ('high', 'Élevé'), ('critical', 'Critique')], default='low', max_length=20)),
                ('last_scan', models.DateTimeField(auto_now=True)),
                ('blocked_connections', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Surveillance Port',
                'verbose_name_plural': 'Surveillance Ports',
                'ordering': ['port'],
            },
        ),
        migrations.CreateModel(
            name='AntiBotField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(help_text='Nom du formulaire (login, register, contact, etc.)', max_length=100)),
                ('field_name', models.CharField(default='website_url', help_text='Nom du champ caché', max_length=100)),
                ('field_label', models.CharField(blank=True, help_text='Label visible si nécessaire', max_length=200)),
                ('is_visible', models.BooleanField(default=False, help_text='Si le champ doit être visible (pour debug)')),
                ('css_classes', models.CharField(blank=True, help_text='Classes CSS pour le champ', max_length=200)),
                ('blocked_submissions', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Champ Anti-Bot',
                'verbose_name_plural': 'Champs Anti-Bot',
                'unique_together': {('form_name', 'field_name')},
            },
        ),
        migrations.CreateModel(
            name='AntiBotDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_ip', models.CharField(max_length=50)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('submitted_value', models.CharField(blank=True, max_length=500)),
                ('form_data', models.JSONField(blank=True, default=dict)),
                ('blocked', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.antibotfield')),
            ],
            options={
                'verbose_name': 'Détection Anti-Bot',
                'verbose_name_plural': 'Détections Anti-Bot',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('port_scan', 'Scan de ports'), ('brute_force', 'Attaque brute force'), ('sql_injection', 'Injection SQL'), ('xss', 'Attaque XSS'), ('malware', 'Malware détecté'), ('honeypot', 'Activation honeypot'), ('suspicious_ip', 'IP suspecte'), ('high_traffic', 'Trafic élevé'), ('system_error', 'Erreur système'), ('other', 'Autre')], default='other', max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyen'), ('high', 'Élevé'), ('critical', 'Critique')], default='medium', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('source_ip', models.CharField(blank=True, max_length=50, null=True)),
                ('affected_system', models.CharField(blank=True, max_length=100)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('telegram_sent', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerte Sécurité',
                'verbose_name_plural': 'Alertes Sécurité',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('active_connections', models.IntegerField(default=0)),
                ('requests_per_minute', models.FloatField(default=0.0)),
                ('blocked_requests', models.IntegerField(default=0)),
                ('suspicious_ips', models.IntegerField(default=0)),
                ('ai_threat_score', models.FloatField(default=0.0)),
                ('bot_detections', models.IntegerField(default=0)),
                ('anomaly_detections', models.IntegerField(default=0)),
                ('network_traffic', models.BigIntegerField(default=0)),
                ('port_scans_detected', models.IntegerField(default=0)),
                ('cpu_usage', models.FloatField(default=0.0)),
                ('memory_usage', models.FloatField(default=0.0)),
                ('disk_usage', models.FloatField(default=0.0)),
                ('active_alerts', models.IntegerField(default=0)),
                ('resolved_alerts_today', models.IntegerField(default=0)),
                ('honeypot_triggers', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Métrique Sécurité',
                'verbose_name_plural': 'Métriques Sécurité',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='marketplace_timesta_4de61e_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=20)),
                ('component', models.CharField(choices=[('auth', 'Authentification'), ('api', 'API'), ('admin', 'Administration'), ('network', 'Réseau'), ('honeypot', 'Honeypot'), ('ai', 'IA'), ('firewall', 'Firewall'), ('other', 'Autre')], default='other', max_length=50)),
                ('message', models.TextField()),
                ('source_ip', models.CharField(blank=True, max_length=50, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log Sécurité',
                'verbose_name_plural': 'Logs Sécurité',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='marketplace_created_7e92a0_idx'), models.Index(fields=['level', '-created_at'], name='marketplace_level_f58fd4_idx'), models.Index(fields=['component', '-created_at'], name='marketplace_compone_51cbe8_idx')],
            },
        ),
    ]
