# Generated by Django 6.0.3 on 2026-05-17 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0058_add_vulnerability_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='recharge_message',
            field=models.TextField(blank=True, null=True, verbose_name='Message de recharge'),
        ),
        migrations.AddField(
            model_name='profile',
            name='recharge_selfie',
            field=models.ImageField(blank=True, null=True, upload_to='recharge_selfies/', verbose_name='Selfie de recharge'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('ai_admin', 'Administrateur IA'), ('admin_secondary', 'Admin secondaire'), ('support_employee', 'Soutien / employé'), ('buyer_seller', 'Acheteur / Vendeur'), ('delivery_employee', 'Employé livraison'), ('agent', 'Agent')], default='buyer_seller', max_length=20),
        ),
    ]
