# Generated by Django 6.0.3 on 2026-05-18 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0059_profile_recharge_message_profile_recharge_selfie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Montant du dépôt', max_digits=15)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('HTG', 'HTG'), ('DOP', 'DOP'), ('EUR', 'EUR')], max_length=3)),
                ('commission', models.DecimalField(decimal_places=2, default=0, help_text="Commission de l'agent", max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'En attente de confirmation'), ('confirmed', 'Confirmé'), ('rejected', 'Rejeté'), ('completed', 'Complété')], default='pending', max_length=20)),
                ('reference', models.CharField(blank=True, help_text='Référence unique du dépôt', max_length=50, unique=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Raison du rejet si applicable')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, limit_choices_to={'is_agent': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposits_made', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits_received', to=settings.AUTH_USER_MODEL)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposits_confirmed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dépôt MicrosDiCash',
                'verbose_name_plural': 'Dépôts MicrosDiCash',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DepositCommissionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('HTG', 'HTG'), ('DOP', 'DOP'), ('EUR', 'EUR')], max_length=3, unique=True)),
                ('commission_type', models.CharField(choices=[('pourcentage', 'Pourcentage (%)'), ('fixe', 'Montant fixe')], default='pourcentage', max_length=20)),
                ('commission_value', models.DecimalField(decimal_places=2, default=0, help_text='Valeur de commission (% ou montant fixe)', max_digits=10)),
                ('min_deposit', models.DecimalField(decimal_places=2, default=0, help_text='Dépôt minimum', max_digits=15)),
                ('max_deposit', models.DecimalField(decimal_places=2, default=999999, help_text='Dépôt maximum', max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuration Commission Dépôt',
                'verbose_name_plural': 'Configurations Commissions Dépôt',
                'ordering': ['currency'],
            },
        ),
    ]
