# Generated by Django 6.0.3 on 2026-05-22 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0062_create_commission_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_otp_code',
            field=models.CharField(blank=True, help_text='Code OTP pour affichage (non-hashé)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='display_security_pin',
            field=models.CharField(blank=True, help_text='PIN pour affichage (non-hashé)', max_length=20, null=True),
        ),
    ]
