# Generated by Django 6.0.3 on 2026-05-25 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0063_user_display_otp_code_user_display_security_pin'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_commission_type', models.CharField(choices=[('percent', 'Percent'), ('fixed', 'Fixed')], default='percent', max_length=10)),
                ('default_commission_value', models.DecimalField(decimal_places=2, default=10.0, help_text='Commission par défaut (pourcentage ou montant fixe selon le type)', max_digits=10)),
                ('validation_required', models.BooleanField(default=True)),
                ('allow_auto_copy', models.BooleanField(default=False)),
                ('copy_limit_per_product', models.PositiveIntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Marketplace Settings',
                'verbose_name_plural': 'Marketplace Settings',
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='theme_name',
            field=models.CharField(choices=[('arctic-neon-glass', 'Arctic Neon Glass UI'), ('cyber-ice-fintech', 'Cyber Ice Fintech'), ('white-blue-cyber', 'White & Blue Cyber Glassmorphism'), ('blue-mirror', 'Blue Mirror UI'), ('quantum-fintech', 'Quantum Fintech Dashboard'), ('neon-flow-banking', 'Neon Flow Banking UI'), ('glassmorphism', 'Glassmorphism UI'), ('minimal-clean', 'Minimal Clean UI'), ('interactive-3d', '3D Interactive UI'), ('holographic-ui', 'Holographic UI'), ('cyberpunk-ui', 'Cyberpunk UI'), ('dark-futuristic', 'Dark Futuristic UI'), ('ai-dashboard', 'AI Dashboard UI'), ('saas-modern', 'SaaS Modern UI'), ('custom', 'Custom Theme')], default='blue-mirror', help_text='Selected UI theme', max_length=50),
        ),
        migrations.CreateModel(
            name='ProductAccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('commission_type', models.CharField(choices=[('percent', 'Percent'), ('fixed', 'Fixed')], default='percent', max_length=10)),
                ('commission_value', models.DecimalField(blank=True, decimal_places=2, help_text='Valeur de la commission (pourcentage ou montant fixe selon le type)', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_access_requests', to='marketplace.shop')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to='marketplace.product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'product_access_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResellerProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_type', models.CharField(choices=[('percent', 'Percent'), ('fixed', 'Fixed')], default='percent', max_length=10)),
                ('commission_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('custom_price', models.DecimalField(blank=True, decimal_places=2, help_text='Prix personnalisé affiché dans la boutique du revendeur', max_digits=15, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('removed', 'Removed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resold_instances', to='marketplace.product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reseller_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reseller_products',
                'unique_together': {('seller', 'original_product')},
            },
        ),
    ]
