# Generated by Django 6.0.3 on 2026-05-25 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0064_marketplacesettings_alter_profile_theme_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resellerproduct',
            name='copied_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='copied_instances', to='marketplace.product'),
        ),
    ]
