# Generated by Django 6.0.3 on 2026-05-25 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0065_resellerproduct_copied_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacesettings',
            name='max_active_copies_per_seller',
            field=models.PositiveIntegerField(default=50, help_text='Nombre maximum de copies actives par vendeur'),
        ),
        migrations.CreateModel(
            name='MarketplaceSellerCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_type', models.CharField(choices=[('percent', 'Pourcentage'), ('fixed', 'Montant fixe')], default='percent', max_length=10)),
                ('commission_value', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_commissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commission spéciale par vendeur',
                'verbose_name_plural': 'Commissions spéciales par vendeur',
                'unique_together': {('seller',)},
            },
        ),
    ]
