# Generated by Django 6.0.3 on 2026-05-26 00:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0066_marketplacesettings_max_active_copies_per_seller_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='notes',
            field=models.TextField(blank=True, help_text='Commentaires additionnels sur le retrait'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='processed_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_agent': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_withdrawals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente de confirmation'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('completed', 'Complété')], default='pending', max_length=20),
        ),
    ]
