# Generated by Django 6.0.3 on 2026-05-26 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0067_withdrawalrequest_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalCommissionTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='HTG', max_length=10)),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_fee', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('system_fee', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('agent_fee', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tranche Commission Retrait',
                'verbose_name_plural': 'Tranches Commission Retrait',
                'ordering': ['min_amount'],
            },
        ),
        migrations.AlterModelOptions(
            name='commissionconfig',
            options={'ordering': ['nom'], 'verbose_name': 'Configuration Commission', 'verbose_name_plural': 'Configurations Commissions'},
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='fee_agent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='fee_system',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='fee_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.CreateModel(
            name='AdminCommissionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('create', 'Création'), ('update', 'Mise à jour'), ('delete', 'Suppression'), ('toggle', 'Activation / Désactivation')], max_length=20)),
                ('target_name', models.CharField(max_length=200)),
                ('target_type', models.CharField(default='WithdrawalCommissionTier', max_length=100)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal Modification Commission',
                'verbose_name_plural': 'Journaux Modification Commission',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WithdrawalTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='HTG', max_length=10)),
                ('account_type', models.CharField(blank=True, max_length=20)),
                ('fee_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('fee_system', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('fee_agent', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('type', models.CharField(default='withdrawal', max_length=50)),
                ('status', models.CharField(default='completed', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_withdrawal_transactions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal_transactions', to=settings.AUTH_USER_MODEL)),
                ('withdrawal_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_transactions', to='marketplace.withdrawalrequest')),
            ],
            options={
                'verbose_name': 'Transaction Retrait',
                'verbose_name_plural': 'Transactions Retrait',
                'ordering': ['-created_at'],
            },
        ),
    ]
