# Generated by Django 6.0.3 on 2026-05-30

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0069_transfercommissiontier_transfer_transferlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='distribution_balance_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='R\u00e9serve de distribution de commissions - USD', max_digits=15),
        ),
        migrations.AddField(
            model_name='wallet',
            name='distribution_balance_htg',
            field=models.DecimalField(decimal_places=2, default=0, help_text='R\u00e9serve de distribution de commissions - HTG', max_digits=15),
        ),
        migrations.AddField(
            model_name='wallet',
            name='distribution_balance_peso',
            field=models.DecimalField(decimal_places=2, default=0, help_text='R\u00e9serve de distribution de commissions - PESO', max_digits=15),
        ),
        migrations.AddField(
            model_name='wallet',
            name='distribution_balance_eur',
            field=models.DecimalField(decimal_places=2, default=0, help_text='R\u00e9serve de distribution de commissions - EUR', max_digits=15),
        ),
        migrations.AddField(
            model_name='marketplacesettings',
            name='commission_admin_share',
            field=models.DecimalField(decimal_places=2, default=Decimal('70.00'), help_text='Part de la commission vers\u00e9e au portefeuille admin (%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='marketplacesettings',
            name='commission_distribution_share',
            field=models.DecimalField(decimal_places=2, default=Decimal('30.00'), help_text='Part de la commission vers\u00e9e \u00e0 la r\u00e9serve de distribution (%)', max_digits=5),
        ),
        migrations.CreateModel(
            name='CommissionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Catégorie de commission',
                'verbose_name_plural': 'Catégories de commission',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserCommissionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='marketplace.commissioncategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attribution Catégorie Commission',
                'verbose_name_plural': 'Attributions Catégorie Commission',
                'unique_together': {('user', 'category')},
            },
        ),
        migrations.CreateModel(
            name='CommissionDistributionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('distribution', 'Distribution de commissions'), ('return', 'Retour au système'), ('assignment', 'Attribution de catégorie'), ('unassignment', 'Retrait de catégorie')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_distribution_logs', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_distribution_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal de distribution de commission',
                'verbose_name_plural': 'Journaux de distribution de commission',
                'ordering': ['-created_at'],
            },
        ),
    ]
