# Generated by Django 6.0.3 on 2026-06-01 06:12

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0070_add_commission_distribution_and_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='SDISolSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_members', models.PositiveSmallIntegerField(default=10)),
                ('contribution_amount_usd', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=12)),
                ('contribution_amount_htg', models.DecimalField(decimal_places=2, default=Decimal('2600.00'), max_digits=12)),
                ('frequency', models.CharField(choices=[('weekly', 'Hebdomadaire'), ('monthly', 'Mensuelle')], default='weekly', max_length=10)),
                ('withdrawal_fee_htg', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=12)),
                ('withdrawal_fee_usd', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SDI Sol Settings',
                'verbose_name_plural': 'SDI Sol Settings',
            },
        ),
        migrations.CreateModel(
            name='SDISolMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('ontime', 'À jour'), ('late', 'En retard'), ('pending', 'En attente')], default='pending', max_length=10)),
                ('last_payment_date', models.DateTimeField(blank=True, null=True)),
                ('next_due_date', models.DateTimeField(blank=True, null=True)),
                ('total_paid_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_paid_htg', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sdi_sol_member', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SDI Sol Member',
                'verbose_name_plural': 'SDI Sol Members',
                'ordering': ['position', 'joined_at'],
            },
        ),
        migrations.CreateModel(
            name='SDISolPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('HTG', 'HTG')], max_length=3)),
                ('fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('receipt_number', models.CharField(max_length=100, unique=True)),
                ('due_date', models.DateTimeField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('completed', 'Effectué'), ('late', 'En retard')], default='pending', max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='marketplace.sdisolmember')),
            ],
            options={
                'verbose_name': 'SDI Sol Payment',
                'verbose_name_plural': 'SDI Sol Payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
