# Generated by Django 6.0.3 on 2026-06-01 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0071_sdisolsettings_sdisolmember_sdisolpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='peuple_commission_balance_eur',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Commission Peuple - EUR', max_digits=15),
        ),
        migrations.AddField(
            model_name='wallet',
            name='peuple_commission_balance_htg',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Commission Peuple - HTG', max_digits=15),
        ),
        migrations.AddField(
            model_name='wallet',
            name='peuple_commission_balance_peso',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Commission Peuple - PESO', max_digits=15),
        ),
        migrations.AddField(
            model_name='wallet',
            name='peuple_commission_balance_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Commission Peuple - USD', max_digits=15),
        ),
    ]
