# Generated by Django 6.0.3 on 2026-06-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0072_wallet_peuple_commission_balance_eur_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('url', models.CharField(blank=True, default='#', max_length=255)),
                ('icon_class', models.CharField(blank=True, default='fa-solid fa-circle-check', max_length=120)),
                ('description', models.TextField(blank=True, help_text='Utilisez des retours à la ligne pour séparer les points de menu.')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Élément de menu activité',
                'verbose_name_plural': 'Éléments de menu activité',
                'ordering': ['order', 'title'],
            },
        ),
    ]
