# Generated by Django 6.0.3 on 2026-06-02 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0073_activitymenuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdisolmember',
            name='admin_approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sdisolmember',
            name='admin_approved',
            field=models.BooleanField(default=False),
        ),
    ]
