# Generated by Django 6.0.3 on 2026-06-03 02:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0074_sdisolmember_admin_approval_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name="Titre de l'annonce")),
                ('description', models.TextField(verbose_name='Description détaillée')),
                ('property_type', models.CharField(choices=[('maison', 'Maison'), ('appartement', 'Appartement'), ('terrain', 'Terrain'), ('local_commercial', 'Local commercial')], max_length=20, verbose_name='Type de bien')),
                ('listing_type', models.CharField(choices=[('vente', 'À vendre'), ('location', 'À louer')], max_length=20, verbose_name='Statut')),
                ('status', models.CharField(choices=[('disponible', 'Disponible'), ('loue', 'Loué'), ('vente_en_cours', 'Vente en cours'), ('indisponible', 'Indisponible')], default='disponible', max_length=20, verbose_name='État')),
                ('address', models.CharField(max_length=255, verbose_name='Adresse complète')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('neighborhood', models.CharField(blank=True, max_length=100, verbose_name='Quartier')),
                ('country', models.CharField(default='Haiti', max_length=100, verbose_name='Pays')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix')),
                ('currency', models.CharField(default='HTG', max_length=3, verbose_name='Devise')),
                ('total_area', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Surface totale (m²)')),
                ('bedrooms', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Nombre de chambres')),
                ('bathrooms', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Nombre de salles de bain')),
                ('has_parking', models.BooleanField(default=False, verbose_name="Dispose d'un parking")),
                ('has_garden', models.BooleanField(default=False, verbose_name="Dispose d'un jardin")),
                ('has_balcony', models.BooleanField(default=False, verbose_name="Dispose d'un balcon")),
                ('has_gate', models.BooleanField(default=False, verbose_name="Dispose d'une clôture/barrière")),
                ('approval_status', models.CharField(choices=[('en_attente', 'En attente'), ('approuvee', 'Approuvée'), ('rejetee', 'Rejetée')], default='en_attente', max_length=20, verbose_name="Statut d'approbation")),
                ('rejected_reason', models.TextField(blank=True, verbose_name='Raison du rejet')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Publié le')),
                ('view_count', models.IntegerField(default=0, verbose_name='Nombre de vues')),
                ('contact_count', models.IntegerField(default=0, verbose_name='Nombre de contacts')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_properties', to=settings.AUTH_USER_MODEL, verbose_name='Agent immobilier')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_properties', to=settings.AUTH_USER_MODEL, verbose_name='Approuvé par')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='real_estate_properties', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
            ],
            options={
                'verbose_name': 'Propriété immobilière',
                'verbose_name_plural': 'Propriétés immobilières',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Ajouté le')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='marketplace.property', verbose_name='Propriété')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_properties', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Favoris immobilier',
                'verbose_name_plural': 'Favoris immobilier',
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='real_estate/%Y/%m/', verbose_name='Image')),
                ('image_type', models.CharField(choices=[('facade', 'Façade'), ('avant', 'Surface avant'), ('entree', 'Porte principale'), ('fenetres', 'Fenêtres'), ('salon', 'Salon'), ('cuisine', 'Cuisine'), ('chambre', 'Chambre'), ('salle_bain', 'Salle de bain'), ('toilettes', 'Toilettes'), ('parking', 'Parking'), ('balcon', 'Balcon'), ('jardin', 'Jardin'), ('cloture', 'Clôture / Barrière'), ('autre', 'Autre')], max_length=20, verbose_name="Type d'image")),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Légende')),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Téléchargé le')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='marketplace.property', verbose_name='Propriété')),
            ],
            options={
                'verbose_name': 'Image de propriété',
                'verbose_name_plural': 'Images de propriété',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_type', models.CharField(choices=[('avis', 'Avis positif'), ('probleme', 'Problème'), ('arnaque', 'Signalement arnaque'), ('donnees_incorrectes', 'Données incorrectes'), ('autre', 'Autre')], max_length=20, verbose_name="Type d'avis")),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('rating', models.IntegerField(default=5, help_text='1 à 5 étoiles', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Note (1-5)')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Vérifié')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Approuvé')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Modéré par')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='marketplace.property', verbose_name='Propriété')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Avis immobilier',
                'verbose_name_plural': 'Avis immobilier',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RealEstateMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lu le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('admin_replied', models.BooleanField(default=False, verbose_name='Admin a répondu')),
                ('admin_reply_blocked', models.BooleanField(default=False, verbose_name='Réponse admin bloquée')),
                ('admin_reply_reason', models.TextField(blank=True, verbose_name='Raison du blocage')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='marketplace.property', verbose_name='Propriété')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_real_estate_messages', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_real_estate_messages', to=settings.AUTH_USER_MODEL, verbose_name='Expéditeur')),
            ],
            options={
                'verbose_name': 'Message immobilier',
                'verbose_name_plural': 'Messages immobilier',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RealEstateNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('nouveau_message', 'Nouveau message'), ('propriete_approuvee', 'Propriété approuvée'), ('propriete_rejetee', 'Propriété rejetée'), ('favori_ajoute', 'Favori ajouté'), ('propriete_contactee', 'Propriété contactée'), ('avis_recu', 'Avis reçu')], max_length=30, verbose_name='Type de notification')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lu le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketplace.property', verbose_name='Propriété')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='real_estate_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Notification immobilier',
                'verbose_name_plural': 'Notifications immobilier',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['city', 'property_type'], name='marketplace_city_25fd60_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['approval_status', 'listing_type'], name='marketplace_approva_b1078a_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['-created_at'], name='marketplace_created_b7575c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='propertyfavorite',
            unique_together={('user', 'property')},
        ),
    ]
