# Generated by Django 6.0.3 on 2026-06-03 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0075_property_propertyfavorite_propertyimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_real_estate_member',
            field=models.BooleanField(default=False, verbose_name='Membre Immobilier'),
        ),
        migrations.CreateModel(
            name='RealEstateMembershipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('sample_property_title', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Rejetée')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='real_estate_membership_requests', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Demande d'adhésion immobilier",
                'verbose_name_plural': "Demandes d'adhésion immobilier",
                'ordering': ['-created_at'],
            },
        ),
    ]
