# Generated by Django 6.0.3 on 2026-06-03 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0076_profile_is_real_estate_member_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name="Titre de l'annonce")),
                ('message', models.TextField(help_text="Contenu principal de l'annonce", verbose_name='Message administratif')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('scheduled', 'Planifiée'), ('archived', 'Archivée')], default='inactive', max_length=20, verbose_name='Statut')),
                ('is_priority', models.BooleanField(default=False, help_text="Les annonces prioritaires s'affichent en premier", verbose_name='Annonce prioritaire')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activée')),
                ('start_date', models.DateTimeField(blank=True, help_text='Quand cette annonce devient active', null=True, verbose_name='Date de début')),
                ('end_date', models.DateTimeField(blank=True, help_text='Quand cette annonce devient inactive', null=True, verbose_name='Date de fin')),
                ('background_color', models.CharField(default='#1a3a52', help_text='Format hexadécimal (#RRGGBB)', max_length=7, verbose_name='Couleur de fond')),
                ('text_color', models.CharField(default='#ffffff', help_text='Format hexadécimal (#RRGGBB)', max_length=7, verbose_name='Couleur du texte')),
                ('accent_color', models.CharField(default='#00bcd4', help_text='Format hexadécimal (#RRGGBB)', max_length=7, verbose_name="Couleur d'accent")),
                ('scroll_speed', models.CharField(choices=[('very_slow', 'Très lent (20px/s)'), ('slow', 'Lent (40px/s)'), ('normal', 'Normal (60px/s)'), ('fast', 'Rapide (80px/s)'), ('very_fast', 'Très rapide (100px/s)')], default='normal', max_length=20, verbose_name='Vitesse de défilement')),
                ('enable_loop', models.BooleanField(default=True, verbose_name='Défilement en boucle')),
                ('animation_effect', models.CharField(choices=[('slide', 'Glissement'), ('fade', 'Fondu'), ('bounce', 'Rebond'), ('wave', 'Vague'), ('pulse', 'Pulsation')], default='slide', max_length=50, verbose_name="Effet d'animation")),
                ('icon', models.CharField(default='📢', help_text="Emoji qui s'affiche avant le message", max_length=20, verbose_name='Emoji/Icône')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('view_count', models.IntegerField(default=0, verbose_name='Nombre de vues')),
                ('click_count', models.IntegerField(default=0, verbose_name='Nombre de clics')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to=settings.AUTH_USER_MODEL, verbose_name='Créée par')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_announcements', to=settings.AUTH_USER_MODEL, verbose_name='Dernière modification par')),
            ],
            options={
                'verbose_name': 'Annonce administrative',
                'verbose_name_plural': 'Annonces administratives',
                'ordering': ['-is_priority', '-created_at'],
                'indexes': [models.Index(fields=['-is_priority', '-created_at'], name='marketplace_is_prio_0546e7_idx'), models.Index(fields=['status', 'is_active'], name='marketplace_status_8fd633_idx'), models.Index(fields=['start_date', 'end_date'], name='marketplace_start_d_2ff09d_idx')],
            },
        ),
        migrations.CreateModel(
            name='AdminAnnouncementPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_level', models.CharField(choices=[('view', 'Lecture seulement'), ('create', 'Créer'), ('edit', 'Modifier'), ('delete', 'Supprimer'), ('manage_all', 'Gestion complète')], default='view', max_length=20, verbose_name='Niveau de permission')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'octroi")),
                ('admin', models.ForeignKey(limit_choices_to={'role__in': ['super_admin', 'ai_admin', 'admin_secondary']}, on_delete=django.db.models.deletion.CASCADE, related_name='announcement_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Administrateur')),
                ('granted_by', models.ForeignKey(blank=True, help_text="Généralement l'Administrateur Principal", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_announcement_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Permission accordée par')),
            ],
            options={
                'verbose_name': 'Permission Annonce',
                'verbose_name_plural': 'Permissions Annonces',
                'unique_together': {('admin',)},
            },
        ),
    ]
