# Generated by Django 6.0.3 on 2026-06-03 23:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0077_adminannouncement_adminannouncementpermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiKanePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('duration_days', models.PositiveIntegerField(choices=[(30, '30 jours'), (60, '60 jours'), (90, '90 jours'), (180, '6 mois'), (365, '12 mois'), (730, '24 mois')])),
                ('commission_fixed', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('commission_variable', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('bonus_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan Ti Kanè',
                'verbose_name_plural': 'Plans Ti Kanè',
                'ordering': ['duration_days', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TiKaneAccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('identity_document', models.ImageField(blank=True, null=True, upload_to='tikane/identity_documents/')),
                ('passport_document', models.ImageField(blank=True, null=True, upload_to='tikane/passports/')),
                ('driver_license_document', models.ImageField(blank=True, null=True, upload_to='tikane/driver_licenses/')),
                ('selfie', models.ImageField(blank=True, null=True, upload_to='tikane/selfies/')),
                ('acceptance_clause', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', "En attente d'approbation"), ('approved', 'Approuvé'), ('refused', 'Refusé'), ('suspended', 'Suspendu')], default='pending', max_length=20)),
                ('account_number', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('tikaned_id', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tikane_reviews', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tikane_requests', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_requests', to='marketplace.tikaneplan')),
            ],
            options={
                'verbose_name': 'Demande Ti Kanè',
                'verbose_name_plural': 'Demandes Ti Kanè',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='TiKaneAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=30, unique=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('pending', 'En attente'), ('closed', 'Fermé'), ('suspended', 'Suspendu')], default='active', max_length=20)),
                ('unique_identifier', models.CharField(max_length=50, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_deposits', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_withdrawals', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('is_sdi_managed', models.BooleanField(default=True)),
                ('manager_name', models.CharField(blank=True, max_length=255)),
                ('manager_phone', models.CharField(blank=True, max_length=50)),
                ('manager_email', models.EmailField(blank=True, max_length=254)),
                ('manager_logo', models.ImageField(blank=True, null=True, upload_to='tikane/manager_logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tikane_account', to='marketplace.tikaneaccessrequest')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tikane_account', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='marketplace.tikaneplan')),
            ],
            options={
                'verbose_name': 'Compte Ti Kanè',
                'verbose_name_plural': 'Comptes Ti Kanè',
                'ordering': ['-opened_at'],
            },
        ),
    ]
