# Generated by Django 6.0.3 on 2026-06-05 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0079_create_initial_tikane_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='tikane_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tikane_deposits', to='marketplace.tikaneaccount'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='tikane_deposit',
            field=models.BooleanField(default=False, verbose_name='Dépôt Ti Kanè'),
        ),
        migrations.AddField(
            model_name='tikaneaccount',
            name='maturity_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
