# Generated by Django 6.0.3 on 2026-06-05 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0080_deposit_tikane_account_deposit_tikane_deposit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiKaneDailyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('paid', 'Payer'), ('unpaid', 'Non payer')], default='paid', max_length=10)),
                ('paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_payments', to='marketplace.tikaneaccount')),
                ('deposit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tikane_daily_payments', to='marketplace.deposit')),
            ],
            options={
                'verbose_name': 'Paiement journalier Ti Kanè',
                'verbose_name_plural': 'Paiements journaliers Ti Kanè',
                'ordering': ['account', 'day_number'],
                'unique_together': {('account', 'day_number')},
            },
        ),
    ]
