# Generated by Django 6.0.3 on 2026-06-07 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0081_tikanedailypayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeautyAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_type', models.CharField(choices=[('home', 'Service à domicile'), ('studio', 'Service au studio')], default='studio', max_length=20)),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField()),
                ('address', models.CharField(blank=True, help_text='Adresse à domicile ou adresse de rendez-vous au studio', max_length=300)),
                ('instructions', models.TextField(blank=True, help_text='Informations supplémentaires pour le technicien')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('completed', 'Complété'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('payment_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beauty_appointments', to='marketplace.product')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_beauty_appointments', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beauty_appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Réservation Beauté',
                'verbose_name_plural': 'Réservations Beauté',
                'ordering': ['-scheduled_date', '-scheduled_time', '-created_at'],
            },
        ),
    ]
