# Generated by Django 6.0.3

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0082_beautyappointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeautyStudioRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='pending', max_length=20)),
                ('studio_name', models.CharField(help_text='Nom du studio de beauté', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description des services proposés')),
                ('phone', models.CharField(blank=True, help_text='Numéro de téléphone du studio', max_length=20)),
                ('address', models.CharField(blank=True, help_text='Adresse du studio', max_length=300)),
                ('specialties', models.CharField(blank=True, help_text='Spécialités (ex: coiffure, maquillage, massages)', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_beauty_studios', to=settings.AUTH_USER_MODEL)),
                ('approved_shop', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beauty_studio_request', to='marketplace.shop')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='beauty_studio_request', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande Studio Beauté',
                'verbose_name_plural': 'Demandes Studio Beauté',
                'ordering': ['-created_at'],
            },
        ),
    ]
