# Generated by Django 6.0.3 on 2026-06-08 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0083_beautystudiorequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeautyStudioService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('manicure', 'Manucure'), ('pedicure', 'Pédicure'), ('haircare', 'Soin Capillaire'), ('african_braids', 'Tresse Africaine')], default='manicure', max_length=30)),
                ('title', models.CharField(help_text='Nom du service', max_length=120)),
                ('price_ht', models.DecimalField(decimal_places=2, help_text='Prix en USD (devise interne)', max_digits=15)),
                ('image', models.ImageField(blank=True, help_text='Photo du service', null=True, upload_to='beauty_services/%Y/%m/')),
                ('description', models.TextField(blank=True, help_text='Description courte du service')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beauty_services', to='marketplace.shop')),
            ],
            options={
                'verbose_name': 'Service Studio Beauté',
                'verbose_name_plural': 'Services Studio Beauté',
                'ordering': ['service_type', 'title'],
            },
        ),
    ]
