# Generated by Django 6.0.3 on 2026-06-08 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0084_beautystudioservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCoverPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Photo de couverture du studio', upload_to='shop_covers/%Y/%m/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_photos', to='marketplace.shop')),
            ],
            options={
                'verbose_name': 'Photo de couverture studio',
                'verbose_name_plural': 'Photos de couverture studio',
                'ordering': ['sort_order', 'uploaded_at'],
            },
        ),
    ]
