# Generated by Django 6.0.3 on 2026-06-09 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0086_course_courseassignment_assignmentsubmission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicianProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150)),
                ('contact_name', models.CharField(help_text='Nom du responsable', max_length=120)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('city_region', models.CharField(blank=True, default='', max_length=120)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('services', models.CharField(blank=True, default='', help_text='Services proposés séparés par des virgules', max_length=500)),
                ('references', models.TextField(blank=True, default='', help_text='Références professionnelles (une par ligne)')),
                ('website', models.URLField(blank=True, default='')),
                ('whatsapp', models.CharField(blank=True, default='', max_length=80)),
                ('facebook', models.URLField(blank=True, default='')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='technician_logos/')),
                ('photo_1', models.ImageField(blank=True, null=True, upload_to='technician_photos/')),
                ('photo_1_desc', models.CharField(blank=True, default='', max_length=200)),
                ('photo_2', models.ImageField(blank=True, null=True, upload_to='technician_photos/')),
                ('photo_2_desc', models.CharField(blank=True, default='', max_length=200)),
                ('photo_3', models.ImageField(blank=True, null=True, upload_to='technician_photos/')),
                ('photo_3_desc', models.CharField(blank=True, default='', max_length=200)),
                ('photo_4', models.ImageField(blank=True, null=True, upload_to='technician_photos/')),
                ('photo_4_desc', models.CharField(blank=True, default='', max_length=200)),
                ('photo_5', models.ImageField(blank=True, null=True, upload_to='technician_photos/')),
                ('photo_5_desc', models.CharField(blank=True, default='', max_length=200)),
                ('is_published', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technician_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Technicien',
                'verbose_name_plural': 'Profils Techniciens',
                'ordering': ['-created_at'],
            },
        ),
    ]
