# Generated by Django 6.0.3 on 2026-06-11 00:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0087_technicianprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacesettings',
            name='enable_real_estate_auto_loan',
            field=models.BooleanField(default=False, verbose_name='Prêt automatique immobilier'),
        ),
        migrations.AddField(
            model_name='marketplacesettings',
            name='real_estate_membership_fee_htg',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=15, verbose_name='Frais d’adhésion immobilier (HTG)'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='real_estate_loan_balance_htg',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Solde du prêt immobilier en cours - HTG', max_digits=15),
        ),
    ]
