# Generated by Django 6.0.3 on 2026-08-29 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0097_sitebanner_access_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='banner_block_reason',
            field=models.TextField(blank=True, default='', help_text='Raison du blocage'),
        ),
        migrations.AddField(
            model_name='product',
            name='banner_blocked_at',
            field=models.DateTimeField(blank=True, help_text='Date du blocage', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='banner_blocked_by_admin',
            field=models.ForeignKey(blank=True, help_text='Admin qui a bloqué', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_banner_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='banner_display_allowed',
            field=models.BooleanField(default=True, help_text="Autoriser l'affichage en bannière (par défaut: True si image valide)"),
        ),
    ]
