# Generated by Django 6.0.3 on 2026-09-03 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0100_systemsettings_banner_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriorityGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom du groupe')),
                ('priority', models.PositiveIntegerField(default=100, verbose_name='Priorité')),
                ('weight', models.PositiveIntegerField(default=1, verbose_name='Poids de diffusion')),
                ('is_active', models.BooleanField(default=True, verbose_name='Groupe actif')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de début')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Groupe de priorité',
                'verbose_name_plural': 'Groupes de priorité',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='banner_priority',
            field=models.PositiveIntegerField(default=100, verbose_name='Priorité individuelle'),
        ),
        migrations.AddField(
            model_name='product',
            name='banner_weight',
            field=models.PositiveIntegerField(default=1, verbose_name='Poids individuel'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='banner_visible_to_admins',
            field=models.BooleanField(default=True, verbose_name='Afficher la bannière aux administrateurs'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='principal_banner_visible',
            field=models.BooleanField(default=True, verbose_name='Afficher la bannière à l’administrateur principal'),
        ),
        migrations.AddField(
            model_name='product',
            name='priority_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='marketplace.prioritygroup', verbose_name='Groupe de priorité'),
        ),
    ]
