# Generated by Django 6.0.3 on 2026-09-16 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0102_systemsettings_banner_expand'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Carte active'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='whatsapp_link',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Lien WhatsApp'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='config_type',
            field=models.CharField(choices=[('main', 'Logo Principal'), ('favicon', 'Favicon'), ('footer', 'Logo Footer'), ('support_card', 'Carte Support SDI')], max_length=50, unique=True, verbose_name='Type de configuration'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='site_config/%Y/%m/', verbose_name='Image/Logo'),
        ),
    ]
