# Generated by Django 6.0.3 on 2026-06-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingsplan',
            name='currency',
            field=models.CharField(choices=[('HTG', 'HTG'), ('USD', 'USD'), ('EUR', 'EUR'), ('DOP', 'DOP')], max_length=3),
        ),
    ]
